apiVersion: apps/v1
kind: Deployment
metadata:
  name: managify-backend
  namespace: managify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managify-backend
  template:
    metadata:
      labels:
        app: managify-backend
    spec:
      containers:
        - name: backend
          image: doguhannilt/managify-backend:d1f3d8b521d9c6ffb2da690210794d4ccb0dc4d5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: managify-secrets
                  key: mongo-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: managify-secrets
                  key: mongo-root-password
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@managify-mongo:27017/?authSource=admin"
            - name: MONGO_DB
              value: "managify"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: managify-backend
  namespace: managify
spec:
  selector:
    app: managify-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
