apiVersion: apps/v1
kind: Deployment
metadata:
  name: managify-mongo
  namespace: managify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managify-mongo
  template:
    metadata:
      labels:
        app: managify-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: managify-secrets
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: managify-secrets
                  key: mongo-root-password
            - name: MONGO_INITDB_DATABASE
              value: "managify"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
