apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managify
  namespace: argocd
spec:
  project: default
  source:
    # Replace with your repository URL, e.g. https://github.com/your-org/your-repo
    repoURL: 'https://github.com/doguhanniltextra/managify-go
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: managify
  syncPolicy:
    automated:
      prune: true        # delete resources removed from Git
      selfHeal: true     # revert manual changes in cluster to match Git
    syncOptions:
      - CreateNamespace=true
  # Optional: configure health checks or ignore differences as needed


